# Handle Next.js static files
[[redirects]]
from = "/_next/static/*"
to = "/_next/static/:splat"
status = 200

# Handle public folder assets
[[redirects]]
from = "/image/*"
to = "/image/:splat"
status = 200

[[redirects]]
from = "/icons/*"
to = "/icons/:splat"
status = 200

# Handle all other routes (SPA fallback)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200